services:
    app:
        build: .
        container_name: laravue-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - laravue-network

    db:
        image: mysql:8
        container_name: laravue-db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravue
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "4306:3306"
        networks:
            - laravue-network

    nginx:
        image: nginx:latest
        container_name: laravue-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravue-network

networks:
    laravue-network:
        driver: bridge
